### ISSUE TITLE
Would be great to not render the label if it's not set or empty

### ISSUE THREAD

**Issue by wobba** [jquintozamora/react-taxonomypicker#1]
If you have a custom layout with labels in one column, it would be useful for the control not to render the &lt;label&gt; tag.

**Comment by jquintozamora** [comment]
Hi Mikael (@wobba), 
Thank you for your feeback. 
I have published a new version including the mentioned behavior:

If we set "displayName" prop the <label> will be rendered.
If "displayName" prop is null, undefined or empty then <label> will not render.

You can see that change using the version: "react-taxonomypicker": "0.0.32" or higher.

**Comment by wobba** [comment]
Awesome and very quick :)
