### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by nanddeepn** [jquintozamora/react-taxonomypicker#118]
I am trying the static data
`<TaxonomyPicker
                name="Language"
                displayName="Language"
                defaultOptions={[
                  { label: "English", value: "f50249b6-310d-43b6-aaa6-f0cb46d851bf" },
                  { label: "Spanish", value: "237ca323-1ed8-4199-a49b-a9f7ce4256bf" },
                  { label: "German", value: "44024c7e-f738-4755-90e1-15866327c806" },
                  { label: "Italian", value: "65f67491-bdca-491a-84fa-f6fd913f40fa" },
                ]}
                multi
                showPath
              />`

But, received error
Cannot read property 'toLowerCase' of undefined at below method in TaxonomyPicker.tsx

`private filterOption = (option, filter) => {
        let returned = false;
        const filterBy = this.props.showPath ? ["value", "label", "path"] : ["value", "label"]
        filterBy.forEach((p) => {
            if (option[p].toLowerCase().indexOf(filter.toLowerCase()) !== -1) {
                returned = true;
                return;
            }
        });
        return returned;
    }`

**Comment by jquintozamora** [comment]
Hello @nanddeepn ,

You should also have prop 'path' in your options objects. 
I will update docs accordingly. 

Thanks!
