### ISSUE TITLE
Sp.Taxonomy.js is sometimes not loaded from the correct location

### ISSUE THREAD

**Issue by martinlingstuyl** [jquintozamora/react-taxonomypicker#121]
If my url is *tenant.sharepoint.com/sites/testsite*, the taxonomy JS file is loaded correctly. However, when I am on *tenant.sharepoint.com/sites/testsite/pages/testpage.aspx* the file is not loaded, because it tries to get it from **tenant.sharepoint.com/sites/testsite/pages/testpage.aspx/_layouts/15/sp.taxonomy.js**.

this is an issue because of the implementation of the `getLayoutsPageUrl` function

**Comment by jquintozamora** [comment]
Hello @martinlingstuyl , 

I see. PR are accepted ! Please feel free to contribute.

**Comment by jquintozamora** [comment]
Hello @martinlingstuyl ,

I've just released `react-taxonomypicker@0.0.45`. 

Please let me know if that solves your issue.

**Comment by martinlingstuyl** [comment]
Hi @jquintozamora,

I forked your project and introduced PnP JS. So I won't be using this one with JSOM anymore. I could have closed the issue to prevent you from investing your time, sorry about that.

Martin
