### ISSUE TITLE
Path Label displaying full path in SP2016

### ISSUE THREAD

**Issue by nvgopi** [jquintozamora/react-taxonomypicker#122]
Environment : Sharepoint 2016 On Premise
Version of Taxonomy picker : "react-taxonomypicker": "0.0.45",

Hi, When i try to select the label as per the demo version at https://jquintozamora.github.io/react-taxonomypicker/, It picks only the label instead of the full path. 

When i used the same control with the props as per the sample above, It is selecting the entire path as per the screenshot, 

Wondering if there is a way to only pick the label instead of the full path. Attaching a screenshot. 
![TaxonomyPicker](https://user-images.githubusercontent.com/31060544/71416720-bc4fac80-2687-11ea-83f4-a2f26ec6200a.png)

Wanted to see if I can just display the label name instead of the full path.

**Comment by jquintozamora** [comment]
Hi @nvgopi ,
Thanks for your comment,

There is a prop to enable / disable that behavour.

showPath={true} or showPath -> will enable path as a label
showPath={false} or don't use showPath prop -> will show label
