### ISSUE TITLE
Objects are not valid as a React child (found: ReferenceError: SP is not defined)

### ISSUE THREAD

**Issue by samir-farid** [jquintozamora/react-taxonomypicker#2]
When using the defaultOptions, everything works fine and the component gets rendered with values, but when I remove the defaultOptions and supply a termsetguid and termsetname to retrieve terms from Office 365, the component is rendered but there are no values in the dropdown and the console logs the following error:

Error: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=ReferenceError%3A%20SP%20is%20not%20defined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

On the facebook site it says the error is:

Objects are not valid as a React child (found: ReferenceError: SP is not defined)

**Comment by jquintozamora** [comment]
Hi @samir-farid ,

Thank you for your feedback.

For me sounds like in your current environment doesn't exist SP.js file (or hasn't been loaded).
Please, could you give me more information:

- Are you using this component within a SharePoint page (CEWQ or SEWQ) ?
- Which version of react-taxonomypicker are you using in your package.json?

Thanks!

**Comment by samir-farid** [comment]
Hi José, Sorry I figured out what was wrong, when I compared your SPFX project with mine I found out about the _loadSPJSOMScripts function which I couldn't find in the documentation. When I implemented it, it worked.

Thanks for taking the time to reply.

**Comment by prabhat9999** [comment]
hi samir-farid  , I m having the same issue when i implemented in spfx could you please explained how it would be solved??
many thanks
