### ISSUE TITLE
Query whether the parent tag can be included

### ISSUE THREAD

**Issue by rr17** [jquintozamora/react-taxonomypicker#3]
Hi,

This is not a issue . I wanna know whether the control can display suggestion similar to the default sharepoint taxonomy control where it displays the parent tag in square braces. 
Please advise

**Comment by jquintozamora** [comment]
Hi @rr17 ,
I'd like to let you know that latest version 0.0.37 has included the path of the term. 

Please let me know if that satisfy your need.
