### ISSUE TITLE
Path label not display correctly

### ISSUE THREAD

**Issue by pmatthews05** [jquintozamora/react-taxonomypicker#4]
Bug: 
After installing and testing out "path" in new version 0.37, if there are more than one sub-term underneath the termset then the path seperator '>' isn't showing in all places.

For example:
1 level deep shows
"Finance and Corporate > Reporting"
2 or more levels deep shows
"Finance and Corporate;Reporting > Quarterly

It should show
"Finance and Corporate > Reporting > Quarterly.

![taxonomy picker bug](https://user-images.githubusercontent.com/6736509/34938557-b0840c96-f9e0-11e7-8a9b-d4360f987147.png)

**Comment by jquintozamora** [comment]
Hi @pmatthews05 ,
Thank you for your feedback and for the idea.
I've updated package to react-taxonomypicker@0.0.38.

It should solve the issue. Please let me know!

**Comment by pmatthews05** [comment]
Thanks.
