### ISSUE TITLE
Sometimes not working on Android

### ISSUE THREAD

**Issue by EA12** [jquintozamora/react-taxonomypicker#48]
Sometimes the TaxonomyPicker shows no options to choose when running under Android mobile Device (Reproducable with Samsung Galaxy S7).
It is working on Desktop and on IPad.

We use it in SPFx-WebParts on SharePoint-Online-Tenants.

Version: 0.0.40
`"react-taxonomypicker": {
  "version": "0.0.40",
  "resolved": "https://registry.npmjs.org/react-taxonomypicker/-/react-taxonomypicker-0.0.40.tgz",
  "integrity": "sha1-68uqOtsHxV1/U/CgmeuG4+d6Be8=",
  "requires": {
	"@types/react-select": "1.2.3",
	"react-select": "1.2.1"
  }
}
`
We have the required components installed.
This is our Definition:

`<TaxonomyPicker
	name="RoomTags"
	id="roomTags"
	displayName={strings.Keywords}
	termSetGuid={this.props.keywordTermsetId}
	termSetName="Room Tags"
	termSetCountMaxSwapToAsync={100}
	defaultValue={this.props.keyWords}
	onPickerChange={this.keywordChanged}
	ignoreAccents={false}
	multi
	placeholder={strings.KeywordPlaceholder}
/>`

**Comment by jquintozamora** [comment]
Hello @EA12 , 
Thanks for the feedback on that. 
As I have no Android device is going to be difficult to debug that issue. Could you please debug you application using your device connected (https://raygun.com/blog/debug-android-chrome/) and please let me know what is the error message or any other debug information you can get.

Thanks!
