### ISSUE TITLE
TaxonomyPicker fails to show terms in IE

### ISSUE THREAD

**Issue by LeemansBE** [jquintozamora/react-taxonomypicker#5]
When running in Internet Explorer (11) the terms do not seem to be rendered in the dropdown.
Error in console:
![image](https://user-images.githubusercontent.com/33486494/36088426-8cb9125e-0fd7-11e8-82f3-3b911fcda436.png)

The error seems to be triggerd by the filterOption method in TaxonomyPicker.tsx.
This method does a .includes() on certain string values. After a quick search I found that String.prototype.includes is not supported in Internet Explorer (or Opera).  Changing the .includes to an .indexOf seems to fix the problem:
![image](https://user-images.githubusercontent.com/33486494/36088633-59206c5c-0fd8-11e8-85a9-ff767d8a5b3d.png)

Regards,
Bart

**Comment by jquintozamora** [comment]
Hi Bart,

Thank you for your feedback,

I've solved the issue, it should work now if you download the version react-taxonomypicker@0.0.39.
