### ISSUE TITLE
elements are not rendered from the sharepoint online

### ISSUE THREAD

**Issue by prabhat9999** [jquintozamora/react-taxonomypicker#6]
When using the defaultOptions, everything works fine and the component gets rendered with values, but when I remove the defaultOptions and supply a termsetguid and termsetname to retrieve terms from Office 365, the component is rendered but there are no values in the dropdown and also it doesnt show any error on the console screen.

**Comment by jquintozamora** [comment]
Hello @prabhat9999 , 
Please could you use Network tab in developer tools or wireshark to see if the query has been raised to the server ?

**Comment by prabhat9999** [comment]
thanks :-) fixed by giving external file references in config.json file
