### ISSUE TITLE
Path label not display correctly on SPO

### ISSUE THREAD

**Issue by Krak86** [jquintozamora/react-taxonomypicker#82]
I am using 0.0.42 version. 
In SharePoint Online (SPO) I have doubled term labels, when I set 'showPath' attribute to true.

I made screens of termset structure in SPO.

Here is Term Store structure:
![termset](https://user-images.githubusercontent.com/11327481/44453365-2d490500-a5f9-11e8-8aab-e1728f973db2.PNG)

and here is how it displays in component's label:
![taxonomyreact](https://user-images.githubusercontent.com/11327481/44453375-333ee600-a5f9-11e8-8322-8ebb4f36d38c.PNG)

According to issue #4 I think this is not fixed :(

**Comment by Krak86** [comment]
I found a solution. 
In the 'renderOption' method of 'TaxonomyPicker.tsx' class the next changes should be implemented:

existing method:

>     private renderOption = (option) => {
        const fullPath = option
            && option.path
            && typeof option.path === "string"
            && option.path.split(";").join(" > ") || undefined;
        return (
            <div
                title={option.label}
            >
                {this.props.showPath ? fullPath ? <span>{fullPath} > </span> : null : null}
                {option.label}
            </div>
        );
    }

new method:

>     private renderOption = (option) => {
        const fullPath = option
            && option.path
            && typeof option.path === "string"
            && option.path.split(";").join(" > ") || undefined;
        return (
            <div
                title={option.label}
            >
                { this.props.showPath ? (fullPath ? <span>{fullPath} </span> : null ) : option.label }
            </div>
        );
    }

**Comment by jquintozamora** [comment]
Hi @Krak86 ,
Thanks for the feedback.
I'll update the code or if you feel like to create a PR go for it and I'll review.
